### ISSUE TITLE
Still in use?

### ISSUE THREAD

**Issue by isuftin** [USGS-CIDA/MLR_Spring_Boot_Docker#8]
@kmschoep-usgs  With everything going on, do you think this is still going to be used? Can it be deleted?

**Comment by kmschoep-usgs** [comment]
I think that's a question for @zmoore-usgs

**Comment by zmoore-usgs** [comment]
I think it can probably be deleted

**Comment by jread-usgs** [comment]
@isuftin are you doing general clean up or do we need to free up repos for some reason? A little worried about blowing away a repo that _probably_ can be deleted unless there is a need...

**Comment by zmoore-usgs** [comment]
@jread-usgs This project is being superseded by https://github.com/USGS-CIDA/docker-wma-spring-boot-base . We aren't currently running any MLR containers anywhere and all of the MLR docker images are being re-done and will be inheriting from the image linked above instead of this one. My only hesitation on deleting this was in case some other docker image not in the scope of MLR had decided to inherit from this, but perhaps that shouldn't be supported? Not really sure.

@isuftin Perhaps we should just mark it as deprecated for now as we did with https://github.com/USGS-CIDA/docker-aqcu-base and then plan to set a date for removal in the same manner?
